In [1]:
import os
import numpy as np
import pandas as pd
import requests
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
data_file = "/content/sample_data/titanic.txt"
titanic = pd.read_csv(data_file)
print(titanic.shape)
titanic.head()

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
titanic['Sex'] = titanic['Sex'].map({'female':1,'male':0})
titanic['Age'].fillna(value=titanic['Age'].mean(), inplace=True)
titanic['FirstClass'] = titanic['Pclass'].apply(lambda x: 1 if x == 1 else 0)
titanic['SecondClass'] = titanic['Pclass'].apply(lambda x: 1 if x == 2 else 0)

titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  FirstClass  SecondClass  
0         A/5 21171   7.2500   NaN        S           0            0  
1          PC 17599  71.2833   C85        C           1            0  
2  STON/O2. 3101282   7.9250   NaN        S           0            0  
3            113803  53.1000  C123        S           1            0  
4            373450   8.0500   NaN        S           0            0

In [4]:
x_titanic = titanic[['Sex', 'Age', 'FirstClass', 'SecondClass']]
y_titanic = titanic['Survived']

In [5]:
train_x_titanic, test_x_titanic, train_y_titanic, test_y_titanic = \
train_test_split(x_titanic, y_titanic, test_size=0.3, random_state=123)
print(train_x_titanic.head())
print(test_x_titanic.head())

     Sex   Age  FirstClass  SecondClass
416    1  34.0           0            1
801    1  31.0           0            1
512    0  36.0           1            0
455    0  29.0           0            0
757    0  18.0           0            1
     Sex        Age  FirstClass  SecondClass
172    1   1.000000           0            0
524    0  29.699118           0            0
452    0  30.000000           1            0
170    0  61.000000           1            0
620    0  27.000000           0            0


In [6]:
logistic = LogisticRegression(penalty='none')
logistic.fit(train_x_titanic, train_y_titanic)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


LogisticRegression(penalty='none')

In [7]:
print(logistic.intercept_)
print(logistic.coef_)

[-1.08777172]
[[ 2.55838407 -0.04004487  2.38223532  1.05157353]]


In [8]:
print(logistic.score(train_x_titanic, train_y_titanic))
print(logistic.score(test_x_titanic, test_y_titanic))

0.7865168539325843
0.7835820895522388


In [9]:
print(test_x_titanic.head())
print(logistic.predict(test_x_titanic)[0:5])

     Sex        Age  FirstClass  SecondClass
172    1   1.000000           0            0
524    0  29.699118           0            0
452    0  30.000000           1            0
170    0  61.000000           1            0
620    0  27.000000           0            0
[1 0 1 0 0]


In [10]:
test_y_prediction = logistic.predict(test_x_titanic)
print(test_y_titanic.sum())
print(test_y_prediction.sum())
confusion_matrix(test_y_titanic, test_y_prediction)

98
108


array([[136,  34],
       [ 24,  74]])